### ISSUE TITLE
Data processing of image/assets/media don't work using EXT:TYPO3 CMS Content Blocks 

### ISSUE THREAD

**Issue by web2date** [benjaminkott/bootstrap_package#1444]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v11.5 LTS
* [ x] Can you reproduce the problem on TYPO3 v12.4 LTS
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

Building new contentelements via ContentBlocks in a sitepackage to Bootstrap_package works partially, but the dataprocessing of image/assets/media fails. The fields in Backend are working, one can add an image, but in Frontend the image is missing and the debug says "image => 1 (integer)" and no file_reference is build.
Removing bootstrap_package from the system, content_blocks is working as expected!

## Steps to Reproduce

1. Install EXT:ContentBlocks
2. Create a Content Block skeleton in your terminal inside your sitepackage
3. Define a simple ContentElement
```
name: vendor/content-block-name
group: common
fields:
    -
        identifier: header
        useExistingField: true
    -
        identifier: bodytext
        useExistingField: true
        enableRichtext: true
    -
        identifier: image
        useExistingField: true
``` 
4. Add a <f:debug>{data}</f:debug> to Frontend.html (and Fluid for the 3 fields)
5. Add this ContentElement to a page in Backend and fill all necessary fields

### Expected behavior

I want to see header, bodytext and image

### Actual behavior

I see Header and bodytext

### Screenshots

Wrong
<img width="235" alt="Bildschirmfoto 2023-11-13 um 16 03 09" src="https://github.com/benjaminkott/bootstrap_package/assets/8898397/de117b26-58cb-48ca-8a68-a0bbb527e6fa">
Correct
<img width="589" alt="Bildschirmfoto 2023-11-13 um 16 01 08" src="https://github.com/benjaminkott/bootstrap_package/assets/8898397/ff535d3f-87fc-4929-9dfb-a0f736d533df">

## Versions
TYPO3v12.4.7 / BSP 14.0.7 / Content_Blocks 0.1.6
