### ISSUE TITLE
RTE config "extraPlugins"

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#1463]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v11.5 LTS
* [x] Can you reproduce the problem on TYPO3 v12.4 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

All plugins for RTE (bootstrappackage_address, bootstrappackage_box, ...) not showing up in RTE any more. I guess because of new CKEditor version:

> TYPO3 v12 ships with CKEditor 5, which is a completely new, rewritten editor compared to CKEditor 4 which was shipped since TYPO3 v8.

In TYPO3 v11 with EXT:bootstrap_package v12 it works.

It seems, configuration should be something like that?
```
    importModules:
      - { module: '@typo3/rte-ckeditor/plugin/whitespace.js', exports: [ 'Whitespace' ] }
```

---

Configuration option "toolbarGroups" is also deprecated, you should use "toolbar" now, e.g.:

```
editor:
    config:
        toolbar:
            items:
                - heading
                - style
                - '|'
                - bold
                - italic
```
