### ISSUE TITLE
Full Screen Width Content without setting frame to "No frame"?

### ISSUE THREAD

**Issue by oliverschloebe** [benjaminkott/bootstrap_package#1550]
# Support

## Description

Howdy, maybe I'm missing something here but I'm struggling finding a way to create a full width content element while retaining all the bg color / image settings by settings.

Seems like you only get full width by setting `frame_class` to `none` and sacrificing the bg color / image settings, right?

Thanks!

**Comment by sukitsubaki** [comment]
I'm not sure if I got it right, but you could try the following:

1. Place your content element inside a container (1 column).
2. Set the container to "no frame."
3. Leave the frame of your initial content element as it is.
4. If needed, adjust the background color of the container.

Hope that helps!

**Comment by oliverschloebe** [comment]
Thanks for the reply!

> 4. If needed, adjust the background color of the container.

Well the issue is I cannot set the container's background color if it's set to "no frame."

**Comment by oliverschloebe** [comment]
> Yes, that was a no-brainer… What exactly are you trying to accomplish? Are you looking to have a content element with a specific background color and possibly an image that extends fully to the edges of the screen (borderless/full-width) without any frame padding or margins?

Yeah exactly that.. basically I'm trying to do checkerboard design contents like this

![Image](https://github.com/user-attachments/assets/7f78906f-8294-4c18-8fb6-445e50040bc0)

**Comment by sukitsubaki** [comment]
I took a quick look at this. When selecting "no border," all classes are removed from the container div or none are added. I was able to solve this as follows:

**In TYPO3 Backend:**
`Page > Edit root or regular page > Resources > PageTS config`
```ts
TCEFORM {
    tt_content.frame_layout.addItems {
        oliver-checkerboard = Checkerboard
    }
}
```

**CSS**
```css
.frame-layout-oliver-checkerboard { /* top and bottom space */
    margin: 0;
    padding: 0;
}

.frame-layout-oliver-checkerboard .frame-container { /* left and right space */
    margin: 0;
    padding: 0;
    max-width: 100% !important;
}
```

This way, you can select `Checkerboard` as `Frame layout` for the content element, which removes all surrounding borders while keeping the background color. I'm sure there's a more elegant solution, but this works too for now. :-)
