### ISSUE TITLE
Webfonts not working in IE

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#751]
The webfonts aren't working in all Internet Explorer versions and other browsers, that doesn't support woff2 font files, because bootstrap_package downloads the CSS file from Google servers and caches it (via class GoogleFontService).

Google delivers different font files, depending on user agent (e.g. woff for IE, woff2 for modern browsers).
E.g. for url https://fonts.googleapis.com/css?family=Roboto:300,300italic,400,400italic,700
Google answers with this for IE:

```css
@font-face {
  font-family: 'Roboto';
  font-style: italic;
  font-weight: 300;
  src: local('Roboto Light Italic'), local('Roboto-LightItalic'), url(https://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjASc6CsI.woff) format('woff');
}
```
